teams_regions = {
    '100 THIEVES': 'North America',
    'AFREECA FREECS': 'Korea',
    'AHQ ESPORTS CLUB': 'PCS',
    'ANARCHY': 'Korea',
    'APK PRINCE': 'Korea',
    'BANGKOK TITANS': 'SEA',
    'BBQ OLIVERS': 'Korea',
    'BEŞIKTAŞ ESPORTS': 'Turkey',
    'CHINA (NATIONAL TEAM)': 'China',
    'CHINESE TAIPEI (NATIONAL TEAM)': 'LMS',
    'CHUNGNAM': 'Korea',
    'CJ ENTUS': 'Korea',
    'CJ ENTUS BLAZE': 'Korea',
    'CJ ENTUS FROST': 'Korea',
    'CLOUD9': 'North America',
    'CLUTCH GAMING': 'North America',
    'COUNTER LOGIC GAMING': 'North America',
    'DAMWON GAMING': 'Korea',
    'DETONATION FOCUSME': 'Japan',
    'DRAGONX': 'Korea',
    'DRX': 'Korea',
    'DWG KIA': 'Korea',
    'E-MFIRE': 'Korea',
    'EDWARD GAMING': 'China',
    'ESC EVER': 'Korea',
    'EU LCS ALLSTARS': 'Europe',
    'EVER8 WINNERS': 'Korea',
    'FLASH WOLVES': 'LMS',
    'FNATIC': 'Europe',
    'FREDIT BRION': 'Korea',
    'FUNPLUS PHOENIX': 'China',
    'G2 ESPORTS': 'Europe',
    'GAMANIA BEARS': 'LMS',
    'GAMINGGEAR.EU': 'CIS',
    'GE TIGERS': 'Korea',
    'GEN.G': 'Korea',
    'GIGABYTE MARINES': 'Vietnam',
    'GRIFFIN (KOREAN TEAM)': 'Korea',
    'H2K-GAMING': 'Europe',
    'HANWHA LIFE ESPORTS': 'Korea',
    'HONG KONG (NATIONAL TEAM)': 'LMS',
    'HUYA TIGERS': 'Korea',
    'I MAY': 'China',
    'INCREDIBLE MIRACLE': 'Korea',
    'INCREDIBLE MIRACLE 1': 'Korea',
    'INCREDIBLE MIRACLE 2': 'Korea',
    'INVICTUS GAMING': 'China',
    'JAPAN (NATIONAL TEAM)': 'Japan',
    'JIN AIR GREEN WINGS': 'Korea',
    'JIN AIR GREEN WINGS FALCONS': 'Korea',
    'JIN AIR GREEN WINGS STEALTHS': 'Korea',
    'KINGZONE DRAGONX': 'Korea',
    'KONGDOO MONSTER': 'Korea',
    'KOO TIGERS': 'Korea',
    'KSV ESPORTS': 'Korea',
    'KT ROLSTER': 'Korea',
    'KT ROLSTER A': 'Korea',
    'KT ROLSTER ARROWS': 'Korea',
    'KT ROLSTER BULLETS': 'Korea',
    'KWANGDONG FREECS': 'Korea',
    'LEMONDOGS': 'Europe',
    'LIIV SANDBOX': 'Korea',
    'LMS ALLSTARS': 'LMS',
    'LONGZHU GAMING': 'Korea',
    'LPL ALLSTARS': 'China',
    'MACAU (NATIONAL TEAM)': 'LMS',
    'MACHI ESPORTS': 'PCS',
    'MISFITS GAMING': 'Europe',
    'MVP': 'Korea',
    'MVP BLUE': 'Korea',
    'MVP OZONE': 'Korea',
    'NAJIN BLACK SWORD': 'Korea',
    'NAJIN E-MFIRE': 'Korea',
    'NAJIN SHIELD': 'Korea',
    'NAJIN SWORD': 'Korea',
    'NAJIN WHITE SHIELD': 'Korea',
    'NONGSHIM REDFORCE': 'Korea',
    'OH MY GOD': 'China',
    'ORIGEN': 'Europe',
    'PHONG VŨ BUFFALO': 'Vietnam',
    'PRIME OPTIMUS': 'Korea',
    'QIAO GU REAPERS': 'China',
    'REBELS ANARCHY': 'Korea',
    'ROX TIGERS': 'Korea',
    'ROYAL CLUB': 'China',
    'ROYAL NEVER GIVE UP': 'China',
    'SAMSUNG BLUE': 'Korea',
    'SAMSUNG GALAXY': 'Korea',
    'SAMSUNG OZONE': 'Korea',
    'SAMSUNG WHITE': 'Korea',
    'SANDBOX GAMING': 'Korea',
    'SBENU SONICBOOM': 'Korea',
    'SEOLHAEONE PRINCE': 'Korea',
    'SK TELECOM T1 S': 'Korea',
    'SPLYCE': 'Europe',
    'SUPERMASSIVE ESPORTS': 'Turkey',
    'TAIPEI ASSASSINS': 'LMS',
    'TCL ALLSTARS': 'Turkey',
    'TEAM DYNAMICS': 'Korea',
    'TEAM ICE': 'International',
    'TEAM LIQUID': 'North America',
    'TEAM NB': 'Korea',
    'TEAM WE': 'China',
    'TOP ESPORTS': 'China',
    'TSM': 'North America',}